services:
  - type: web
    name: zerovega
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: INITIAL_VIRTUAL_CASH
        value: 10000.00
      - key: MERCHANT_UPI_ID
        value: harjinder1070-1@okicici
      - key: MERCHANT_NAME
        value: ZeroVega
